### ISSUE TITLE
Use serde_v8 for `serialize_for_snapshotting` and `update_with_snapshotted_data`

### ISSUE THREAD

**Issue by mmastrac** [denoland/deno_core#47]
The `ModuleMap` code is manually serializing data to and from the snapshot which is a fairly large chunk of code. While `serde_v8` may add a little bit of overhead, the code savings will be pretty immense and it should be easier to reason about.

**Comment by nayeemrmn** [comment]
Hopefully that will make it easier to add metadata like a list of extension names which have already been executed.

**Comment by bartlomieju** [comment]
So I believe I originally went with `serde_v8` and decided to do the manual serialization for the performance reason. I'm not sure I want to revert back to serde_v8.

> Hopefully that will make it easier to add metadata like a list of extension names which have already been executed.

Which is something I explicitly wanted to avoid, since that and list of op names amounts to a few hundred strings that will need to be deserialized on each startup. We should measure the performance hit before we commit to doing that.

**Comment by nayeemrmn** [comment]
> and list of op names amounts to a few hundred strings that will need to be deserialized on each startup

Fwiw only extension names are necessary for what I was thinking of, e.g. #50 if I understand it correctly needs to unify the two `.init_ops{,and_esm}()` functions on ext namespaces and then make it const, and I think that would benefit from having metadata on which extensions have had their JS evaluated already.

**Comment by bartlomieju** [comment]
I see, let's just bench it and see if it doesn't cause noticable regressions in the startup time.

**Comment by bartlomieju** [comment]
This is now done.
